version: '3.7'
services:
    app:
        build: .
        command: php -S 0.0.0.0:8120 -t /app
        ports:
            - "8120:8120"
        volumes:
            - ./:/app
    phplite:
        build: .
        command: php -S 0.0.0.0:8121 -t /app/www/phplite
        ports:
            - "8121:8121"
        volumes:
            - ./:/app